# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: studyjstack
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-serverless-dynamodb-101

plugins:
  - serverless-esbuild
  - serverless-offline

build:
  esbuild: false

custom:
  esbuild:
    target: node20
    format: esm
    minify: true
    sourcemap: false
    outputFileExtension: .mjs
    exclude:
      - '@aws-sdk/*'
    platform: node
    concurrency: 10

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:DeleteItem
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ProductsTable.Arn

package:
  individually: true

functions:
  listProducts:
    handler: src/functions/listProducts.handler
    events:
      - httpApi:
          method: GET
          path: /products
  getProduct:
    handler: src/functions/getProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: GET
  createProduct:
    handler: src/functions/createProduct.handler
    events:
      - httpApi:
          path: /products
          method: POST
  updateProduct:
    handler: src/functions/updateProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: PUT
  deleteProduct:
    handler: src/functions/deleteProduct.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: DELETE

# CloudFormation <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html>
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductsTable
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH