# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: studyjstack
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-serverless-framework-101

plugins:
  - serverless-esbuild
  - serverless-offline

build:
  esbuild: false

custom:
  esbuild:
    target: node20
    format: esm
    minify: true
    outputFileExtension: .mjs
    watch:
      pattern: src/**/+.ts

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: get
  insane:
    handler: src/functions/insane.handler
    memorySize: 512
    events:
      - httpApi:
          path: /insane
          method: get